channels:
  - conda-forge
  - bioconda
dependencies:
  - concoct=1.1.0
  - python=3.11.0
  - libopenblas=*=openmp*
  - mkl
  - samtools>=1.9
  - scikit-learn=1.1.*
  - pip:
    - setuptools==75
variables:
  USE_OPENMP: 1
